d = {"Я начинаю": ("I start",),
     "Она начинает?": ("Does she start?",),
     "Они не начинают": ("They don't start", "They do not start"),
     "Ты начнёшь?": ("Will you start?",),
     "Мы не начнём": ("We won't start", "We will not start"),
     "Он начнёт": ("He will start",),
     "Мы начали": ("We started",),
     "Он не начал": ("He didn't start", "He did not start"),
     "Она начала?": ("Did she start?",),

     "Он закончит": ("He will finish",),
     "Они закончат?": ("Will they finish?",),
     "Я не закончу": ("I will not finish", "I won't finish"),
     "Мы закончили?": ("Did we finish?",),
     "Она не закончила": ("She didn't finish", "She did not finish"),
     "Ты закончил": ("You finished",),
     "Я заканчиваю": ("I finish",),
     "Они не заканчивают": ("They don't finish", "They do not finish"),
     "Мы заканчиваем?": ("Do we finish?",),

     "Они не любили": ("They didn't love", "They did not love"),
     "Я буду любить": ("I will love",),
     "Он любит?": ("Does he love?",),
     "Они не любят": ("They don't love", "They do not love"),
     "Мы любили": ("We loved",),
     "Они любили?": ("Did they love?",),
     "Ты не будешь любить": ("You won't love", "You will not love"),
     "Она будет любить?": ("Will she love?",),
     "Я не люблю": ("I don't love", "I do not love"),

     "Ты не помог": ("You didn't help", "You did not help"),
     "Он помог?": ("Did he help?",),
     "Я помог": ("I helped",),
     "Мы помогаем?": ("Do we help",),
     "Они не помогают": ("They do not help", "They don't help"),
     "Я помогаю": ("I help",),
     "Она поможет?": ("Will she help?",),
     "Ты не поможешь": ("You will not help", "You won't help"),
     "Мы будем помогать?": ("Will we help?",),

     "Мы не жили": ("We didn't live", "We did not live"),
     "Ты жил?": ("Did you live?",),
     "Я жил": ("I lived",),
     "Он живёт": ("He lives",),
     "Она не живёт": ("She doesn't live", "She does not live"),
     "Они живут?": ("Do they live?",),
     "Ты не будешь жить": ("You won't live", "You will not live"),
     "Они будут жить?": ("Will they live?",),
     "Я буду жить": ("I will live",),

     "Он будет надеяться?": ("Will he hope?",),
     "Мы не будем надеяться": ("We won't hope", "We will not hope"),
     "Я буду надеяться": ("I will hope",),
     "Ты не надеешься": ("You don't hope", "You do not hope"),
     "Они надеются?": ("Do they hope?",),
     "Она надеется": ("She hopes",),
     "Он не надеется": ("He doesn't hope", "He does not hope"),
     "Мы надеялись": ("We hoped",),
     "Ты надеялся?": ("Did you hope?",),

     "Я не гулял": ("I didn't walk", "I did not walk"),
     "Мы гуляем?": ("Do we walk?",),
     "Он гулял?": ("Did he walk?",),
     "Он не гуляет": ("He doesn't walk", "He does not walk"),
     "Я пойду пешком": ("I will walk",),
     "Она гуляет": ("She walks",),
     "Вы будете гулять?": ("Will you walk?",),
     "Они шли пешком": ("They walked",),
     "Мы не будем гулять": ("We won't walk", "We will not walk"),

     "Мы хотели": ("We wanted",),
     "Она хотела?": ("Did she want?",),
     "Ты не хотел": ("You didn't want", "You did not want"),
     "Я захочу?": ("Will I want",),
     "Он не захочет": ("He won't want", "He will not want"),
     "Мы захотим": ("We will want",),
     "Хочу ли я?": ("Do I want?",),
     "Она хочет": ("She wants",),
     "Они не хотят": ("They don't want", "They do not want"),

     "Она учится": ("She learns",),
     "Он не учится": ("He doesn't learn", "He does not learn"),
     "Она будет учиться?": ("Will she learn?",),
     "Ты не будешь учиться": ("You won't learn", "You will not learn"),
     "Мы учились": ("We learnt", "We learned"),
     "Они не учились": ("They didn't learn", "They did not learn"),
     "Они учатся": ("They learn",),
     "Мы учимся?": ("Do we learn?",),
     "Она училась?": ("Did she learn?",),

     "Он не будет преподавать": ("He will not teach", "He won't learn"),
     "Она преподавала?": ("Did she teach?",),
     "Я преподавал": ("I taught",),
     "Мы будем преподавать": ("We will teach",),
     "Ты не преподаёшь": ("You don't teach", "You do not teach"),
     "Они преподают?": ("Do they teach?",),
     "Я буду преподавать?": ("Will I teach?",),
     "Она не преподавала": ("She didn't teach", "She did not teach"),
     "Он преподаёт": ("He teaches",),

     "Он работает": ("He works",),
     "Они не будут работать": ("They won't work", "They will not work"),
     "Ты работаешь?": ("Do you work?",),
     "Мы не работаем": ("We don't work", "We do not work"),
     "Она будет работать?": ("Will she work?",),
     "Они работали?": ("Did they work?",),
     "Ты не работал": ("You didn't work", "You did not work"),
     "Я буду работать": ("I will work",),
     "Она работала": ("She worked",),

     "Она делает": ("She makes",),
     "Он не сделал": ("He didn't make?", "He did not make?"),
     "Они сделают?": ("Will they make?",),
     "Мы не делаем": ("We don't make", "We do not make"),
     "Я сделал": ("I made",),
     "Ты делаешь": ("You make",),
     "Она не сделает": ("She will not make", "She won't make"),
     "Он сделал?": ("Did he make?",),
     "Ты сделаешь?": ("Will you make?",),

     "Я думаю": ("I think",),
     "Мы не думали": ("We didn't think", "We did not think"),
     "Они подумают?": ("Will they think?",),
     "Ты думал?": ("Did you think?",),
     "Они думали": ("They thought",),
     "Он не подумает": ("He will not think", "He won't think"),
     "Она не думает": ("She doesn't think", "She does not think"),
     "Мы думаем?": ("Do we think?",),
     "Ты подумаешь": ("You will think",),

     "Она изучает": ("Does she study?",),
     "Я не изучил": ("I didn't study", "I did not study"),
     "Мы будем изучать?": ("Will we study?",),
     "Они будут изучать": ("They will study",),
     "Ты не изучишь": ("You will not study", "You won't study"),
     "Он изучает?": ("Does he study?",),
     "Я не буду изучать": ("I won't study", "I will not study"),
     "Они изучали?": ("Did they study?",),
     "Мы изучали?": ("Did we study?",),

     "Я чувствую": ("I feel",),
     "Он почувствует?": ("Will he feel?",),
     "Мы не чувствовали": ("We didn't feel", "We did not feel"),
     "Ты не почувствуешь": ("You won't feel", "You will not feel"),
     "Она будет чувствовать": ("She will feel",),
     "Они чувствовали": ("They felt",),
     "Он чувствует?": ("Does he feel?",),
     "Она почувствует": ("Will she feel?",),
     "Я не чувствую": ("I don't feel", "I do not feel"),

     "Они будут беспокоиться?": ("Will they worry?",),
     "Я беспокоюсь": ("I worry",),
     "Мы не беспокоились": ("We didn't worry", "We did not worry"),
     "Ты будешь беспокоиться?": ("Will you worry?",),
     "Она не беспокоится": ("She doesn't worry", "She does not worry"),
     "Они беспокоятся": ("They worry",),
     "Мы беспокоились": ("We worried",),
     "Я не буду беспокоиться": ("I will not worry", "I won't worry"),
     "Он беспокоился?": ("Did he worry?",)}