d = {"Он продал ей это": ("He sold her this",),
     "Она продаёт машины": ("She sells cars",),
     "Мои друзья не продали квартиру": ("My friends didn't sell the flat", "My friends did not sell the flat"),
     "Когда ты продал телефон?": ("When did you sell the phone?",),
     "Зачем ты продаёшь это?": ("Why do you sell this?",),
     "Мы не будем продавать это": ("We will not sell it", "We won't sell it"),
     "Где ты продашь машину?": ("Where will you sell the car?",),
     "Я не продаю свои вещи": ("I don't sell my things", "I do not sell my things"),
     "Твой отец продаст это?": ("Will your father sell it?",),

     "Когда ты расскажешь ей?": ("When will you tell her?",),
     "Зачем ты ему рассказала?": ("Why did you tell him?",),
     "Где ты рассказываешь это?": ("Where do you tell this?",),
     "Почему она рассказывает это?": ("Why does she tell it?",),
     "Ты расскажешь им?": ("Will you tell them?",),
     "Я всё тебе рассказал": ("I told you everything",),
     "Ты не рассказал мне": ("You didn't tell me", "You did not tell me"),
     "Она рассказывает историю": ("She tells a story",),
     "Мы не рассказываем это": ("We don't tell it", "We do not tell it"),

     "Мы сожгли бумагу": ("We burnt paper",),
     "Где вы сожгли бумагу?": ("Where did you burn paper?",),
     "Когда ты сожжешь это?": ("When will you burn it?",),
     "Где они сжигают лес?": ("Where do they burn the forest?",),
     "Это сгорит завтра": ("It will burn tomorrow",),
     "Мы не зажгли костёр": ("We didn't burn a fire", 'We did not burn a fire'),
     "Зачем ты поджёг это?": ("Why did you burn it?",),
     "Они не сожгут это": ("They won't burn it", "They will not burn it"),
     "Мой брат не сжигает топливо": ("My brother doesn't burn fuel", "My brother does not burn fuel"),

     "Где они сидели?": ("Where did they sit?",),
     "Почему ты сидишь там?": ("Why do you sit there?",),
     "Зачем мы сидим здесь?": ("Why do we sit here?",),
     "Когда ты сядешь?": ("When will you sit?",),
     "Мы не садимся на диван": ("We don't sit on the sofa", "We do not sit on the sofa"),
     "Он сядет с нами?": ("Will he sit with us?",),
     "Мои родители сидели здесь": ("My parents sat here",),
     "Они не сядут за стол": ("They won't sit at the table", "They will not sit at the table"),
     "Мы не сидели вместе": ("We didn't sit together", "We did not sit together"),

     "Он сказал": ("He said",),
     "Зачем они это сказали?": ("Why did they say it?",),
     "Когда ты скажешь?": ("When will you say?",),
     "Я скажу правду": ("I will tell the truth", "I'll tell the truth"),
     "Что он говорит?": ("What does he say?",),
     "Ты не говоришь": ("You don't say", "You do not say"),
     "Где она скажет?": ("Where will she say?",),
     "Мы не сказали": ("We didn't say", "We did not say"),
     "Ты не скажешь": ("You will not say", "You won't say"),

     "Мы не спали дома": ("We did not sleep at home", "We didn't sleep at home"),
     "Где ты спал?": ("Where did you sleep?",),
     "Когда ты уснёшь?": ("When will you sleep?",),
     "Они долго спали": ("They slept a long time",),
     "Мы не спим там": ("We don't sleep there", "We do not sleep there"),
     "Почему он спит?": ("Why does he sleep?",),
     "Я не сплю": ("I don't sleep", "I do not sleep"),
     "Она не уснёт": ("She won't sleep", "She will not sleep"),
     "Ты будешь спать": ("You will sleep",),

     "Я не стану доктором": ("I will not become a doctor", "I won't become a doctor"),
     "Мы станем инженерами": ("We will become engineers",),
     "Когда ты станешь программистом?": ("When will you become a programmer?",),
     "Я стал отцом": ("I became a father",),
     "Как ты стала зомби?": ("How did you become a zombie",),
     "Почему ты становишься лучше?": ("Why do you become better?",),
     "Он становится экспертом": ("He becomes an expert",),
     "Мы не стали студентами": ("We did not become students", "We didn't become students"),
     "Она не становится учителем": ("She does not become a teacher", "She doesn't become a teacher"),

     "Мы стоим здесь": ("We stand here",),
     "Где они стоят?": ("Where do they stand?",),
     "Когда они стояли там?": ("When did they stand there?",),
     "Зачем ты будешь там стоять?": ("Why will you stand there?",),
     "Они стояли с нами": ("They stood with us",),
     "Мой друг стоит без нас": ("My friend stands without us",),
     "Где мы будем стоять?": ("Where will we stand?",),
     "Почему ты стоишь там?": ("Why do you stand there?",),
     "Она не стоит там": ("She does not stand there", "She doesn't stand there"),

     "Они проиграли": ("They lost",),
     "Когда ты проиграл?": ("When did you lose?",),
     "Почему мы проигрываем?": ("Why do we lose?",),
     "Ты не проиграешь им": ("You will not lose them", "You won't lose them"),
     "Мы теряем его": ("We lose him",),
     "Она не проиграет ей": ("She will not lose her", "She won't lose her"),
     "Он не проигрывает нам": ("He doesn't lose us", "He does not lose us"),
     "Мой друг проигрывает тебе": ("My friend loses you",),
     "Ты проиграешь?": ("Will you lose?",),

     "Они установили": ("We set",),
     "Мы поставим это": ("We will set it", "We'll set it"),
     "Когда ты поставишь цели?": ("When will you set the goals?",),
     "Где ты это установил?": ("Where did you set it?",),
     "Зачем она ставит это?": ("Why does she set it?",),
     "Мой друг ставит будильник": ("My friend sets the alarm",),
     "Мы не установим это": ("We will not set it?", "We won't set it"),
     "Мои друзья не ставили": ("My friends did not set", "My friends didn't set"),
     "Я не поставлю": ("I will not set", "I won't set"),

     "Я попробую это": ("I will try it", "I'll try it"),
     "Когда ты пробовал пиццу?": ("When did you try the pizza?",),
     "Почему ты стараешься так сильно?": ("Why do you try so hard?",),
     "Она пробовала": ("She tried",),
     "Мы не попробуем": ("We will not try", "We won't try"),
     "Вы попытаетесь?": ("Will you try?",),
     "Мы постараемся": ("We will try", "We'll try"),
     "Где ты попробуешь кофе?": ("Where will you try coffee",),
     "Я не пробовал": ("I didn't try", "I did not try"),

     "Они играли с нами": ("They played with us",),
     "Мы не играем в эту игру": ("We don't play this game", "We do not play this game"),
     "Ты будешь играть с ними?": ("Will you play with them?",),
     "Когда он сыграет с нами?": ("When will he play with us",),
     "Почему она играет с ним?": ("Why does she play with him?",),
     "Где твой друг играл в футбол?": ("Where did your friend play football?",),
     "Она играет в теннис": ("She plays tennis",),
     "Они не играют в баскетбол": ("They do not play basketball", "They don't play basketball"),
     "Я поиграю с тобой": ("I will play with you", "I'll play with you"),
     }