d = {"Когда ты поверишь мне?": ("When will you believe me?",),
     "Он написал книгу": ("He wrote a book",),
     "Ты полюбишь её?": ("Will you love her?",),
     "Он не работает в офисе": ("He does not work in the office", "He doesn't work in the office"),
     "Они мне не ответили": ("They did not answer me", "They didn't answer me"),
     "Когда ты смотрел этот фильм?": ("When did you watch this film?",),
     "Мы задали им вопрос": ("We asked them a question",),
     "Что ты хочешь?": ("What do you want?",),
     "Кем ты стал?": ("Who did you become?",),
     "Мы не гуляем с ними": ("We don't walk with them", "We do not walk with them"),

     "Когда ты начнёшь?": ("When will you start?",),
     "Ты понимаешь его?": ("Do you understand him?",),
     "Когда ты сломал кровать?": ("When did you break the bed?",),
     "Я попробую это": ("I will try it", "I'll try it"),
     "Ты принесёшь мне воду?": ("Will you bring me water",),
     "Мои друзья путешествуют по Украине": ("My friends travel Ukraine",),
     "Ты купишь мне эту игрушку?": ("Will you buy me this toy?",),
     "Вы переводите текст": ("You translate the text",),
     "Ты звонила моей маме?": ("Did you call my mother?",),
     "Я думал о еде": ("I thought about food",),

     "Ты изменил это?": ("Did you change it?",),
     "Моя подруга мне рассказала": ("My friend told me",),
     "Ты уберешь комнату?": ("Will you clean the room?",),
     "Я преподавал заграницей": ("I taught abroad",),
     "Ты закрыл дверь?": ("Did you close the door?",),
     "Мы пообщались с ней": ("We talked with her", "We talked to her"),
     "Она приходит ко мне": ("She comes to me",),
     "Мой врач берёт деньги": ("My doctor takes money",),
     "Мы не начинаем": ("We do not start", "We don't start"),
     "Мой друг не плавал в детстве": ("My friend did not swim in childhood", "My friend didn't swim in childhood"),

     "Вы построите здание?": ("Will you build a building?",),
     "Мы не изучаем Немецкий": ("We do not study German", "We don't study German"),
     "Ты посчитала?": ("Did you count?",),
     "Мы остановились": ("We stopped",),
     "Что ты режешь?": ("What do you cut",),
     "Они начали": ("They started",),
     "Где ты будешь танцевать?": ("Where will you dance?",),
     "Мы не стояли в центре": ("We did not stand in the centre", "We didn't stand in the centre"),
     "Что ты рисуешь?": ("What do you draw?",),
     "Когда ты потратишь деньги?": ("When will you spend money?",),

     "Зачем ты пил вчера?": ("Why did you drink yesterday?",),
     "Он не говорит по-французски": ("He does not speak French", "He doesn't speak French"),
     "Она хорошо водит": ("She drives well",),
     "Она там не уснёт": ("She will not sleep there", "She won't sleep there"),
     "Ты будешь есть со мной?": ("Will you eat with me?",),
     "Где он сидит?": ("Where does he sit?",),
     "Я упал на стол": ("I fell on the table",),
     "Они плохо поют": ("They sing badly",),
     "Как ты найдёшь меня?": ("How will you find me?",),
     "Ты покажешь мне этот фильм?": ("Will you show me this film?",),

     "Когда ты закончишь?": ("When will you finish?",),
     "Он поставил этот стол здесь": ("He set this table here",),
     "Куда ты летишь?": ("Where do you fly?",),
     "Они отправили сообщение": ("They sent a message",),
     "Почему ты забыла?": ("Why did you forget?",),
     "Она продаёт айфоны на рынке": ("She sells iphones on the market",),
     "Ты получишь письмо?": ("Will you get a letter?",),
     "Что ты сказал?": ("What did you say?",),
     "Что я здесь вижу?": ("What do I see here?",),
     "Мы дадим им деньги": ("We will give them money",),

     "Зачем ты туда идёшь?": ("Why do you go there?",),
     "Мой брат быстро бегал": ("My brother ran fast",),
     "Что читает твой друг?": ("What does your friend read?",),
     "У него есть деньги": ("He has money",),
     "У них денег нет": ("They do not have money", "They don't have money"),
     "Мы их знали": ("We knew them",),
     "Ты меня услышишь?": ("Will you hear them?",),
     "Куда ты положишь телефон?": ("Where will you put the phone?",),
     "Зачем твой босс им помог?": ("Why did your boss help them?",),
     "Их отец играл с нами": ("Their father played with us",),

     "Ты меня уважаешь?": ("Do you respect me?",),
     "Где ты это выучил?": ("Where did you learn it?",),
     "Когда ты откроешь магазин?": ("When will you open the shop?",),
     "Они ушли вчера": ("They went yesterday",),
     "Что ты с этим сделал?": ("What did you do with it?",),
     "Где они живут?": ("Where do they live?",),
     "Ты проиграл вчера?": ("Did you lose yesterday?",),
     "Они работали с ним": ("They worked wit him",),
     "Он работал на него": ("He worked for him",),
     "Мы не работали без неё": ("We did not work without her", "We didn't work without her"),
     }