d = {"Ты не знал этого?": ("Didn't you know it?",),
     "Он не начинает?": ("Doesn't he start?",),
     "Кто купит этот дом?": ("Who will buy this house?",),
     "Кто сломал стол?": ("Who broke the table?",),
     "Кто меняет расписание?": ("Who changes the schedule?",),
     "Ты (разве) не напишешь ему?": ("Won't you text him?",),
     "Кто принёс его сюда?": ("Who brought him here?",),
     "Ты не стал врачом?": ("Didn't you become a doctor?",),
     "Она (разве) не продаёт квартиру?": ("Doesn't she sell the flat?",),
     "Кто тебе поверит?": ("Who will believe you?",),

     "Мы раньше не встречались?": ("Didn't we meet before?",),
     "Ты не понял их?": ("Didn't you understand them?",),
     "Кто идёт с нами?": ("Who goes with us?",),
     "Что ломается чаще?": ("What breaks more often?",),
     "Кто ж знал?": ("Who knew?",),
     "Кому не нравится мясо?": ("Who doesn't like meat?",),
     "Кто выигрывает?": ("Who wins?",),
     "Кто тебе это сказал?": ("Who told you this?",),
     "Какой продукт делает пиццу такой вкусной?": ("What product makes pizza so tasty?",),
     "Какой магазин открывается первым?": ("What shop opens first?",),

     "Кто закроет дверь?": ("Who will close the door?",),
     "Ты не танцуешь?": ("Don't you dance?",),
     "Кто пришёл?": ("Who came?",),
     "Мы не пили вчера?": ("Didn't we drink yesterday?",),
     "Кто посчитает до 10?": ("Who will count to 10?",),
     "Не бегаю ли я?": ("Don't I run?",),
     "Кто закончил последним?": ("Who finished last?",),
     "Мы не летим с ней?": ("Don't we fly with her?",),
     "Почему он не хочет этого?": ("Why doesn't he want it?",),
     "Чего у тебя нет?": ("What don't you have?",),

     "Кто нас услышит?": ("Who will hear us?",),
     "Почему она не помогает им?": ("Why doesn't she help them?",),
     "Что тебя там держит?": ("What holds you there?",),
     "Почему тебе не нравится зелёный цвет?": ("Why don't you like green?",),
     "Кто вчера проиграл?": ("Who lost yesterday?",),
     "Кто это сделал?": ("Who did it?", "Who made it?"),
     "Мы не полетим в Турцию?": ("Won't we fly to Turkey?",),
     "Ты не забыл?": ("Didn't you forget?",),
     "Он (что) не сдал экзамен?": ("Didn't he pass the exam?",),
     "Не дашь (ли) ты им немного денег?": ("Won't you give him some money?",),
     }

d_2 = {
     "Кто пойдёт с ними?": ("Who will go with them?",),
     "Кто шел туда?": ("Who went there?",),
     "Кто пойдёт налево?": ("Who will go left?",),
     "Она не пришла на вечеринку?": ("Didn't she come to the party?",),
     "Они не знаю тебя?": ("Don't they know you?",),
     "Мы не знаем их?": ("Don't we know them??",),
     "Нет ли у вас ручки?": ("Don't you have a pen?",),
     "Нет ли у вас зажигалки?": ("Don't you have a lighter?",),
     "(Разве) у него нет денег?": ("Doesn't he have money?",),
     "Ты не слушаешь рок?": ("Don't you listen to rock?",),

     "Она не слушает Лепса?": ("Doesn't she listen to Leps?",),
     "Кто слушает твою музыку?": ("Who listens to your music?",),
     "Кто не слушает рэп?": ("Who doesn't listen to rap?",),
     "Кто отправил тебе это сообщение?": ("Who sent you this message?",),
     "Кто этого не знает?": ("Who doesn't know it?",),
     "У тебя не было времени?": ("Didn't you have time?",),
     "У тебя не было денег?": ("Didn't you have time?",),
     "У тебя не было желания?": ("Didn't you have a desire?",),
     "Что тебе мешает?": ("What holds you back?",),
     "Что тебе помешало?": ("What held you back?",),

     "Ты не слышишь меня?": ("Don't you hear me?",),
     "Почему она меня не слышит?": ("Why doesn't she hear me?",),
     "Почему они меня не слушают?": ("Why don't they listen to me?",),
     "Почему вы не едите овощи?": ("Why don't you eat vegetables?",),
     "Почему твой друг не помог им?": ("Why didn't your friend help them?",),
     "Кому (вообще) нравится такая музыка?": ("Who likes such music?",),
     "Кто будет слушать твою игру?": ("Who will listen to your play?",),
     "Кто тебя любит?": ("Who loves you?",),
     "Кто любил его?": ("Who loved him?",),
     "Кто тебя не любит?": ("Who doesn't love you?",),

     "Почему ты не любишь это?": ("Why don't you love it?",),
     "Он не делал пиццу?": ("Didn't he make a pizza?",),
     "Мы не делали это раньше?": ("Didn't we do it before?",),
     "Кто делает айфоны?": ("Who makes iphones",),
     "Кто делал первые машины?": ("Who made first cars?",),
     "Кто сделает это лучше?": ("Who will make it better?",),
     "Кто закончит последним?": ("Who will finish last?",),
     "Кто это сюда положил?": ("Who put it here?",),
     "Кто играет в танки?": ("Who plays tanks?",),
     "Кто хорошо говорит на английском?": ("Who speaks English well?",),
}