d = {"Мы берём": ("We take",),
     "Они брали": ("Did they take?",),
     "Ты возьмёшь?": ("Will you take?",),
     "Мы не возьмём": ("We will not take", "We won't take"),
     "Они не брали": ("They didn't take", "They did not take"),
     "Она взяла?": ("Did she take?",),
     "Он берёт": ("He takes",),
     "Ты берёшь?": ("Do you take?",),
     "Я не брал": ("I didn't take", "I did not take"),

     "Я встречу": ("I will meet",),
     "Мы не встретим": ("We won't meet", "We will not meet"),
     "Мы встречаем": ("We meet",),
     "Они не встретят": ("They will not meet", "They won't meet"),
     "Она встречает?": ("Does she meet?",),
     "Мы не встречаем": ("We don't meet", "We do not meet"),
     "Они не встретили": ("They didn't meet", "They did not meet"),
     "Ты встретил?": ("Did you meet?",),
     "Мы встретим?": ("Will we meet?",),

     "Я выиграл": ("I won",),
     "Он выиграл?": ("Did he win?",),
     "Она выигрывает": ("Does she win?",),
     "Они выиграют?": ("Will they win?",),
     "Мы не выиграем": ("We won't win", "We will not win"),
     "Он не выиграл": ("He didn't win", "He did not win"),
     "Я выиграю": ("I will win",),
     "Ты выиграешь?": ("Will you win?",),
     "Они не выигрывают": ("They don't win", "They do not win"),

     "Они говорили": ("They spoke",),
     "Ты говоришь?": ("Do you speak?",),
     "Мы поговорим": ("We will speak",),
     "Он не говорит": ("He doesn't speak", "He does not speak"),
     "Они заговорят?": ("Will they speak",),
     "Она не заговорит": ("She will not speak", "She won't speak"),
     "Ты говорила?": ("Did you speak?",),
     "Мы не говорили": ("We didn't speak", "We did not speak"),
     "Он говорит": ("He speaks",),

     "Мы даём": ("We give",),
     "Они не дали": ("They didn't give", "They did not give"),
     "Вы дадите?": ("Will you give?",),
     "Я дал": ("I gave",),
     "Он даёт?": ("Does he give?",),
     "Ты отдал?": ("Did you give?",),
     "Они не дают": ("They don't give", "They do not give"),
     "Она отдаст": ("She will give",),
     "Мы не дадим": ("We will not give", "We won't give"),

     "Я ел": ("I ate",),
     "Ты ел?": ("Did you eat?",),
     "Они не ели": ("They didn't eat", "They did not eat"),
     "Мы съедим": ("We will eat",),
     "Они не будут есть": ("They won't eat", "They will not eat"),
     "Ты съешь?": ("Will you eat?",),
     "Он ест": ("He eats",),
     "Она ест?": ("Does she eat?",),
     "Они съедят?": ("Will they eat?",),

     "Я забыл": ("I forgot",),
     "Она забывает": ("She forgets",),
     "Ты не забудешь": ("You won't forget", "You will not forget"),
     "Мы забудем": ("We will forget",),
     "Ты не забыл": ("You didn't forget", "You did not forget"),
     "Он забудет?": ("Will he forget?",),
     "Я не забываю": ("I don't forget", "I do not forget"),
     "Мы забыли?": ("Did we forget?",),
     "Ты забываешь?": ("Do you forget?",),

     "Мы не знали": ("We didn't know", "We did not know"),
     "Ты узнаешь?": ("Will you know?",),
     "Он знает": ("He knows",),
     "Ты не знаешь": ("You don't know", "You do not know"),
     "Ты знал?": ("Did you know?",),
     "Они не узнают": ("They will not know", "They won't know"),
     "Я буду знать": ("I will know", "I'll know"),
     "Она знала": ("She knew",),
     "Вы знаете?": ("Do you know?",),

     "У меня есть машина": ("I have a car?",),
     "У тебя нет машины": ("You don't have a car", "You do not have a car"),
     "У нас будет машина?": ("Will we have a car?",),
     "У тебя была машина?": ("Did you have a car?",),
     "У них не было машины": ("They did not have a car", "They didn't have a car"),
     "У нас была машина": ("We had a car",),
     "У него есть машина": ("He has a car",),
     "У неё нет машины": ("She doesn't have a car", "She does not have a car"),
     "У тебя есть машина?": ("Do you have a car?",),

     "Мы кладём": ("We put",),
     "Они положили": ("They put",),
     "Мы положим": ("We will put",),
     "Ты не кладёшь": ("You don't put", "You do not put"),
     "Она кладёт?": ("Does she put?",),
     "Он положит?": ("Will he put?",),
     "Они не кладут": ("They don't put", "They do not put"),
     "Мы не клали": ("We didn't put", "We did not put"),
     "Ты клал?": ("Did you put?",),

     "Я летал": ("I flew",),
     "Они полетят": ("They will fly",),
     "Он не летит": ("He doesn't fly", "He does not fly"),
     "Ты летишь?": ("Do you fly?",),
     "Время летит": ("Time flies",),
     "Она летела?": ("Did she fly?",),
     "Я полечу?": ("Will I fly?",),
     "Ты не полетишь": ("You will not fly", "You won't fly"),
     "Вы летели?": ("Did you fly?",),

     "Я сломал": ("I broke",),
     "Он не сломает": ("He won't break", "He will not break"),
     "Они ломают?": ("Do they break?",),
     "Мы сломаем": ("We will break",),
     "Они не сломали": ("They didn't break", "They did not break"),
     "Мы ломаем": ("We break",),
     "Ты сломаешь?": ("Do you break?",),
     "Она сломает?": ("Will she break?",),
     "Ты сломал?": ("Did you break?",),

     "Мы нашли": ("We found",),
     "Ты нашёл?": ("Did you find?",),
     "Она не находит": ("She doesn't find", 'She does not find'),
     "Мы не нашли": ("We didn't find", "We did not find"),
     "Он находит": ("He finds",),
     "Ты находишь?": ("Do you find?",),
     "Я найду": ("I will find", "I'll find"),
     "Она не найдёт": ("She will not find", "She won't find"),
     "Мы найдём?": ("Will we find?",),

     "Мы начинаем": ("Do we begin?",),
     "Они начнут?": ("Will they begin?",),
     "Ты не начала": ("You didn't begin", "You did not begin"),
     "Мы не начнём": ("We won't begin", "We will not begin"),
     "Вы начали?": ("Did you begin?",),
     "Он начнёт": ("He will begin",),
     "Ты начинаешь?": ("Do you begin?",),
     "Вы не начинаете": ("You do not begin", "You don't begin"),
     "Я начал": ("I began",),

     "Я падаю": ("I fall",),
     "Ты упадёшь?": ("Will you fall?",),
     "Мы падали": ("We fell",),
     "Они не упадут": ("They will not fall", "They won't fall"),
     "Он упал?": ("Did he fall?",),
     "Мы не падаем": ("We don't fall", 'We do not fall'),
     "Вы упадёте": ("Will you fall?",),
     "Они не упали": ("They didn't fall", "They did not fall"),
     "Она падает?": ("Does she fall?",),
     }