d = {
     "Я был в Турции": ("I was in Turkey",),
     "Где ты?": ("Where are you?",),
     "Они не были в Испании": ("They were not in Spain", "They weren't in Spain"),
     "Ты будешь его учителем?": ("Will you be his teacher?",),
     "Она была в Англии?": ("Was she in England?",),
     "Он его начальник": ("He is his boss",),
     "Мы не будем там": ("We will no be there", "We won't be there"),
     "Я не дома сейчас": ("I am not home now", "I'm not home now"),
     "Я буду там": ("I will be there", "I'll be there"),
     "Гугл переводчик - мой лучший друг": ("Google translator is my best friend",),

     "Почему мы здесь?": ("Why are we here?",),
     "Это их дом": ("It is their house", "It's their house"),
     "Ты не будешь его врачом": ("You will not be his doctor", "You won't be his doctor"),
     "Он был твоим студентом?": ("Was he your student?",),
     "Она будет там?": ("Will she be there?",),
     "Я не в парке": ("I am not in the park", "I'm not in the park"),
     "Они будут её студентами": ("They will be her students",),
     "Ты был в Италии?": ("Were you in Italy?",),
     "Она не была в театре": ("She was not in the theatre", "She wasn't in the theatre"),
     "Они не были врачами": ("They were not doctors", "They weren't doctors"),

     "Она не здесь": ("She is not here", "She isn't here"),
     "Он будет там": ("He will be there",),
     "Они не будут нашими водителями": ("They will not be our drivers", "They won't be our drivers"),
     "Вы были везде?": ("Were you here?",),
     "Они твои друзья?": ("Are they your friends?",),
     "Я менеджер": ("I am a manager", "I'm a manager"),
     "Ты будешь его одноклассником?": ("Will you be his classmate?",),
     "Его машина не была в гараже": ("His car was not in the garage", "His car wasn't in the garage"),
     "Я в школе": ("I am at school", "I'm at school"),
     "Ты будешь там?": ("Will you be there?",),

     "Они дома?": ("Are they home?",),
     "Он не занят": ("He is not busy", "He isn't busy"),
     "Я был с вашими друзьями": ("I was with your friends",),
     "Они будут в кафе": ("They will be in the cafe",),
     "Я не буду здесь": ("I will not be here", "I won't be here"),
     "Они не были в больнице": ("They were not in a hospital", "They weren't in a hospital"),
     "Где он был вчера?": ("Where was he yesterday?",),
     "Ты на работе?": ("Are you at work?",),
     "Где ты был?": ("Where were you?",),
     "Кто здесь?": ("Who is here?",),
     }

d_2 = {
     "Он в Лондоне": ("He is in London?",),
     "Я болел на прошлой неделе": ("I was sick last week",),
     "Сегодня холодно": ("It is cold today", "It's cold today"),
     "Она очень красивая?": ("Is she very beautiful?",),
     "Ты будешь известным актером": ("You will be a famous actor", "You'll be a famous actor"),
     "Я не боюсь перемен": ("I am not afraid of changes", "I'm not afraid of changes"),
     "Ты будешь здесь?": ("Will you be here?",),
     "Он был в Америке с ними": ("He was in the US with them",),
     "Мы там": ("We are there",),
     "Мой друг не спортсмен": ("My friend is not a sportsman", "My friend isn't a sportsman"),

     "Она будет известной": ("She will be famous",),
     "Он из Франции?": ("Is he from France?",),
     "Мы не были там": ("We were no there", "We weren't there"),
     "Италия очень красивая": ("Italy is very beautiful",),
     "Его машина чёрная?": ("Is his car black?",),
     "Ты был в Германии в прошлом году?": ("Were you in Germany last year?",),
     "Когда он там был?": ("When was he there?",),
     "Какого цвета этот стол?": ("What colour is this table?",),
     "Двери открыты": ("The doors are open",),
     "Они были в больнице": ("They were in a hospital",),

     "Я скоро буду там": ("I will be there soon", "I'll be there soon"),
     "Ты не был в Испании": ("You were not is Spain", "You weren't in Spain"),
     "Она была их подругой": ("She was their friend",),
     "Они не будут на работе": ("They will not be at work", "They won't be at work"),
     "Мы на улице": ("We are outside", "We're outside"),
     "Ты будешь нашим учителем?": ("Will you be our teacher?",),
     "Ты кто?": ("Who are you?",),
     "Кто я?": ("Who am I?",),
     "Мы были здесь?": ("Were we here?",),
     "Когда она будет в Риме?": ("When will she be in Rome?",),

     "Ты моя надежда": ("You are my hope", "You're my hope"),
     "Они наши студенты?": ("Are they our students?",),
     "Кто там?": ("Who is there?",),
     "Она была везде": ("She was everywhere",),
     "Он – мой любимый актёр": ("He is my favourite actor", "He's my favourite actor"),
     "Она будет твоей?": ("Will she be yours?",),
     "Когда ты был с ними?": ("When were you with them?",),
     "Мой друг будет с тобой. Не волнуйся": ("My friend will be with you. Don't worry",),
     "Она самая лучшая": ("She is the best", "She's the best"),
     "Это их машина ": ("It is their car", "It's their car"),
}