d = {
     "Почему так холодно сегодня?": ("Why is it so cold today?",),
     "В Индии жарко": ("It is hot in India", "It's hot in India"),
     "Когда ты будешь там?": ("When will you be there?",),
     "Это их машина": ("It is our team", "It's our team"),
     "Я не твой друг": ("I am not your friend", "I'm not your friend"),
     "Когда ты там был?": ("When were you there?",),
     "Где ты?": ("Where are you?",),
     "Кто ты?": ("Who are you?",),
     "Какое число самое лучшее?": ("What number is the best?",),
     "Где ты будешь?": ("Where will you be?",),

     "Какой он?": ("What is he?",),
     "Кто они?": ("Who are they?",),
     "Они программисты": ("They are programmers", "They're programmers"),
     "Они не доктора": ("They are not doctors", "They aren't doctors"),
     "Где будет твой друг?": ("Where will your friend be?",),
     "Что это там?": ("What is it there?",),
     "Я в Украине сейчас": ("I am in Ukraine now", "I'm in Ukraine now"),
     "Здесь тепло": ("It is warm here", "It's warm here"),
     "Почему он красный?": ("Why is he red",),
     "Где деньги?": ("Where is money?",),

     "Мой новый ноутбук на столе": ("My new laptop is on the table",),
     "Она моя любимая певица": ("She is my favourite singer", "She's my favourite singer"),
     "Этот фильм не интересный": ("This film is not interesting", "This film isn't interesting"),
     "Он скучный": ("He is boring",),
     "Где ваша маска?": ("Where is your mask?",),
     "Цветы очень красивые": ("Flowers are very beautiful",),
     "Это старый дом": ("It is an old house", "It's an old house"),
     "Тот торт был не вкусным": ("That cake was not tasty", "That cake wasn't tasty"),
     "Я там поздно буду": ("I will be there late", "I'll be there late"),
     "Моё сердце разбито": ("My heart is broken",),

     "Илон Маск богатый": ("Elon Mask is rich",),
     "Его машина очень дорогая": ("His car is very expansive",),
     "Наша квартира очень большая": ("Our flat is very big",),
     "Светофор зелёный": ("The traffic light is green",),
     "Твой друг врач?": ("Is your friend a doctor?",),
     "Почему птицы злые?": ("Why are birds angry?",),
     "Где ты был вчера?": ("Where were you yesterday?",),
     "Кто твой начальник?": ("Who is your boss?",),
     "Мне холодно": ("I am cold", "I'm cold"),
     "Мы были сонные": ("We were sleepy",),
     }

d_2 = {
     "Они не правы": ("They are wrong", "They're wrong"),
     "Мы не были правы": ("We were not right", "We weren't right"),
     "Твой кот не красивый": ("Your cat is not beautiful", "Your cat isn't beautiful"),
     "Мы были в Монако": ("We were in Monaco",),
     "Ты был там?": ("Who was there?",),
     "Хлеб очень вкусный": ("The bread is very tasty",),
     "Они не наши инженеры": ("They are not our engineers", "They aren't our engineers"),
     "Где фонари на улице?": ("Where are street lights in the street?",),
     "Это было давно": ("It was a long time ago",),
     "Почему ты так счастлив?": ("Why are you so happy?",),

     "Вы были в Амстердаме?": ("Were you in Amsterdam?",),
     "Мы не студенты": ("We are not students", "We aren't students"),
     "Их родственники не очень известные": ("Their relatives are not very famous", "Their relatives aren't very famous"),
     "Наша компания очень большая": ("Our company is very big",),
     "Эта пицца была не маленькая": ("This pizza was not small?", "This pizza wasn't small"),
     "Твой торт очень сладкий": ("Your cake is very sweet",),
     "Ты будешь самым лучшим": ("You will be the best",),
     "Где твой адвокат?": ("Where is your lawyer?",),
     "Это кафе не здесь": ("This cafe is not here", "This cafe isn't here"),
     "Это не твоё": ("It is not yours", "It's not yours"),

     "Меня зовут Иван": ("My name is Ivan",),
     "Откуда они?": ("Where are they from?",),
     "Откуда он?": ("Where is he from?",),
     "Откуда твоя подруга?": ("Where is your friend from?",),
     "Твой дядя не будет профессором": ("Your uncle will not be a professor", "Your uncle won't be a professor"),
     "Мой водитель агрессивный": ("My driver is agressive",),
     "Его собака дружелюбная": ("His dog is friendly",),
     "Какой у тебя телефон?": ("What is your phone?", "What's your phone?"),
     "Они из села": ("They are from a village", "They're from a village"),
     "Улица очень чистая": ("The street is very clean",),

     "Моя куртка тёплая": ("My jacket is very warm",),
     "9 моё любимое число": ("9 is my favourite colour",),
     "Синий был моим любимым цветом": ("Blue was my favourite colour",),
     "Биткоин дорогой сейчас": ("Bitcoin is expansive now",),
     "Она ангел": ("She is an angel", "She's an angel"),
     "Как у него дела?": ("How is he?",),
     "Мои студенты весёлые": ("My students are funny",),
     "Он спортсмен?": ("Is he a sportsman?",),
     "Она была на вечеринке?": ("Was she at the party?",),
     "Твои кошки были голодные?": ("Were your cats hungry",),
}