d = {"Почему ты стоишь тут?": ("Why do you stand here?",),
     "Когда ты это потерял?": ("When did you lose it?",),
     "Как он это нашёл?": ("How did he find it?",),
     "Где они бегают?": ("Where do they run?",),
     "Они не знают нас": ("They do not know us", "They don't know us"),
     "Мы взяли еду": ("We took food",),
     "Я видел её": ("I saw her",),
     "Ты чувствуешь это?": ("Do you feel it?",),
     "Где вы встретились?": ("Where did you meet?",),
     "Когда ты читал эту книгу?": ("When did you read this book?",),

     "Когда ты победишь?": ("When will you win?",),
     "Они пошли к ней": ("They went to her",),
     "Мы говорим на английском с ними": ("We speak English with them", "We speak English to them"),
     "Они ушли поздно": ("They left late",),
     "Я сделал это": ("I did it",),
     "Когда ты установишь эту программу?": ("When will you set this program?",),
     "Почему ты держишь мою руку?": ("Why do you hold my hand?",),
     "Он проигрывает": ("He loses",),
     "Почему ты так думаешь?": ("Why do you think so?",),
     "Мои друзья стоят с нами": ("My friends stand with us",),

     "Ты будешь хранить секреты?": ("Will you keep secrets?",),
     "Я не стану пилотом": ("I will not become a pilot", "I won't become a pilot"),
     "Мы подвезём тебя туда": ("We will drive you there", "We'll drive you there"),
     "Ты уснешь там?": ("Will you sleep there?",),
     "Когда они съели пиццу?": ("When did they eat the pizza?",),
     "Я слышал это": ("I heard it",),
     "Они забыли об этом": ("They forgot about it",),
     "Когда ты это сказал?": ("When did you say it?",),
     "Они не знали нас": ("They did not know us", "They didn't know us"),
     "Где он сидит?": ("Where does he sit?",),

     "У него есть новый айфон": ("He has a new iphone",),
     "Где ты разжёг костёр?": ("Where did you burn a fire?",),
     "Куда она положила мой телефон?": ("Where did she put my phone?",),
     "Когда он ей это расскажет?": ("When will he tell it her?",),
     "Мы полетим в Турцию": ("We will fly to Turkey", "We'll fly to Turkey"),
     "Они продали их": ("They sold them",),
     "Я не положил это": ("I did not put it", "I didn't put it"),
     "Зачем она ела?": ("Why did she eat?",),
     "Когда я возьму их?": ("When will I take them?",),
     "Они будут знать её": ("They will know her",),

     "Когда мы будем пить?": ("When will we drink?",),
     "Мои друзья пришли ко мне": ("My friends came to me",),
     "Мы сломали стол": ("We broke the table",),
     "Я принёс тебе торт": ("I brought you a cake",),
     "Мы не нашли их": ("We did not find them", "We didn't find them"),
     "Я учу вас английскому": ("I teach you English",),
     "Где мы начинаем?": ("Where do we start?", "Where do we begin?"),
     "Я отправил тебе подарок": ("I sent you a gift", "I sent you a present"),
     "Я не понял его": ("I did not understand him", "I didn't understand him"),
     "Ты получил сообщение?": ("Did you get the message?",),

     "Мы упадём вместе": ("We will fall together", "We'll fall together"),
     "Где ты купила их?": ("Where did you buy them?",),
     "Мы не напишем книгу": ("We will not write a book", "We won't write a book"),
     "Когда ты покажешь ей это?": ("When will you show it to her?", "When will you show her this?"),
     "Что ты пил?": ("What did you drink?",),
     "Вы заплатите за нас?": ("Will you pay for us?",),
     "Ты побежишь с ними?": ("Will you run with them?",),
     "Она чувствовала тебя": ("She felt you",),
     "Где ты это взял?": ("Where did you take it?",),
     "Куда ты пойдёшь с ним?": ("Where will you go with them?",),

     "Мы увидим тебя на встрече?": ("Will we see you at the meeting?",),
     "Она читает мою книгу": ("She reads my book",),
     "Ты встретишь её?": ("Will you meet her?",),
     "Почему ты говоришь с ней?": ("Why do you speak with her?", "Why do you speak to her?"),
     "Когда ты уходишь?": ("When will you leave?",),
     "Ты дашь им деньги?": ("Will you give them money?",),
     "Я выучу английский": ("I will learn English", "I'll learn English"),
     "Где он сделал ошибку?": ("Where did he make a mistake?",),
     "Я поставил это здесь": ("I set it here",),
     "Она долго держала меня": ("She held a long time",),

     "Когда ты проиграл им?": ("When did you lose them?",),
     "Они думают о нас": ("They think about us",),
     "Где ты стоял?": ("Where did you stand?",),
     "Я отвёз её домой": ("I drove her home",),
     "Они стали популярными": ("They became famous",),
     "Мы съели салат": ("We ate the salad",),
     "Когда ты спал с ними?": ("When did you sleep with them?",),
     "Почему ты работаешь?": ("Why do you work?",),
     "Я не забыл о тебе": ("I did not forget about you", "I didn't forget about you"),
     "Как ты меня слышишь?": ("How do you hear me?",),
     }