d = {"Он не пойдёт к ним": ("He won't go to them", "He will not go to them"),
     "Я иду в кино": ("I go to the cinema",),
     "Она ходила в больницу?": ("Did she go to the hospital?",),
     "Ты не пошёл туда": ("You did not go there", "You didn't go there"),
     "Мы пойдём в спортзал?": ("Will we go to the gym?",),
     "Я шёл домой": ("I went home",),
     "Он не идёт с ней": ("He does not go with her", "He doesn't go with her"),
     "Она пойдёт без нас": ("She will go without us",),
     "Они идут вместе?": ("Do they go together?",),

     "Мы бегаем каждый раз": ("We run every time",),
     "Ты побежишь с нами?": ("Will you run with us?",),
     "Они быстро бегают?": ("Do they run fast?",),
     "Мы не бегаем там": ("We don't run there", "We do not run there"),
     "Я не бегал на стадионе": ("I didn't run on the stadium", "I did not run on the stadium"),
     "Она побежит к ним": ("She will run to them",),
     "Они бежали от неё": ("They ran from her",),
     "Он всегда бегает": ("He always runs",),
     "Я не буду бежать": ("I will not run", "I won't run"),

     "Я не приду сегодня": ("I won't come today", "I will not come today"),
     "Он пришёл домой?": ("Did he come home?",),
     "Она обычно приходит поздно": ("She usually comes late",),
     "Я приду к вам": ("I'll come to you", "I will come to you"),
     "Ты не пришёл к нему": ("You didn't come to him", "You did not come to him"),
     "Ты придёшь один?": ("Will you come alone?",),
     "Мы не приходим на работу": ("We don't come to work", "We do not come to work"),
     "Он не приходит туда": ("He doesn't come there", "He does not come there"),
     "Они не пришли вечером": ("They didn't come in the evening", "They did not come in the evening"),

     "Он следует": ("He follows",),
     "Они не будут следовать": ("They won't follow", "They will not follow"),
     "Я не следовал": ("I did not follow", "I didn't follow"),
     "Ты следовал за ним?": ("Did you follow him?",),
     "Мы следуем за ними?": ("Do we follow them?",),
     "Она последует за тобой?": ("Will she follow you?",),
     "Я последую за вами": ("I will follow you",),
     "Мы будем следовать плану": ("We will follow the plan", "We'll follow the plan"),
     "Ты не следуешь нашим инструкциям": ("You don't follow our instructions", "You do not follow our instructions"),

     "Он не повезёт": ("He won't drive", "He will not drive"),
     "Она ездит": ("She drives",),
     "Они ехали туда?": ("Did they drive there?",),
     "Я отвёз её": ("I drove her",),
     "Ты не подвозил её": ("You didn't drive her", "You did not drive her"),
     "Мы повезём тебя?": ("Will we drive you?",),
     "Они не едут": ("They don't drive", "They do not drive"),
     "Ты подвозишь нас?": ("Do you drive us?",),
     "Они не подвезли его": ("They didn't drive him", "They did not drive him"),

     "Они не остались": ("They did not stay", "They didn't stay"),
     "Я остался у них": ("I stayed with them",),
     "Он останется здесь": ("He will stay here",),
     "Мы остаёмся дома": ("We stay home", "We stay at home"),
     "Ты не остаёшься там": ("You don't stay there", "You do not stay there"),
     "Они остались на ночь?": ("Did they stay the night?",),
     "Она останется навсегда": ("She will stay forever",),
     "Я не останусь с вами": ("I will not stay with you", "I won't stay with you"),
     "Останься со мной": ("Stay with me",),

     "Он спешил": ("He hurried",),
     "Я не спешил туда": ("I didn't hurry there",),
     "Ты будешь спешить?": ("Will you hurry?",),
     "Она не будет спешить": ("She will not hurry", "She won't hurry"),
     "Они не спешили к нам": ("They didn't hurry to us", "They did not hurry to us"),
     "Мы спешили в аэропорт": ("We hurried to the airport",),
     "Ты не спешишь": ("You don't hurry", "You do not hurry"),
     "Мы не торопились": ("We didn't hurry", "We did not hurry"),
     "Я потороплюсь": ("I will hurry", "I'll hurry"),

     "Я прыгаю": ("I jump",),
     "Мы будем прыгать?": ("Will we jump?",),
     "Они будут прыгать": ("They will jump",),
     "Ты прыгнул с моста": ("You jumped off the bridge",),
     "Она не прыгала": ("She didn't jump", "She did not jump"),
     "Она прыгает с ним?": ("Does she jump with him?",),
     "Он не прыгает один": ("He does not jump alone", "He doesn't jump alone"),
     "Они перепрыгнули через забор?": ("They jumped over the fence",),
     "Я не буду прыгать": ("I won't jump", "I will not jump"),

     "Мы не видели вас": ("We didn't see you", "We did not see you"),
     "Они увидят всех?": ("Will they see everybody?", "Will they see everyone?"),
     "Он не увидел их": ("He didn't see them", "He did not see them"),
     "Я увижу это": ("I will see it", "I'll see it"),
     "Ты видел её": ("You saw her",),
     "Она видит нас": ("She sees us",),
     "Мы не увидим его": ("We won't see him", "We will not see him"),
     "Ты видишь их?": ("Do you see them?",),
     "Она видела это?": ("Did she see it?",),

     "Он смотрит на тебя": ("He looks at you",),
     "Мы не будем смотреть туда": ("We won't look there", "We will not look there"),
     "Я смотрел вверх": ("I looked up",),
     "Ты посмотришь назад": ("You will look back",),
     "Она не смотрела мне в глаза": ("She didn't look in my eyes", "She did not look in my eyes"),
     "Они смотрели на неё?": ("Did they look at her?",),
     "Почему ты туда смотришь?": ("Why do you look there?",),
     "Я не смотрю на них": ("I don't look at them", "I do not look at them"),
     "Он посмотрит на меня?": ("Will he look at me?",),

     "Ты смотрел футбол?": ("Did you watch football?",),
     "Она не смотрит фильмы": ("She doesn't watch films", "She does not watch films"),
     "Мы не смотрели телевизор": ("We did not watch TV", "We didn't watch TV"),
     "Ты смотришь новости?": ("Do you watch news?",),
     "Мы не смотрим комедии": ("We don't watch comedies", "We do not watch comedies"),
     "Ты посмотришь со мной фильм ужасов?": ("Will you watch a horror movie with me?",),
     "Я не буду смотреть это": ("I won't watch it", "I will not watch it"),
     "Они посмотрят игру на улице": ("They will watch the game outside",),
     "Он смотрит теннис": ("He watches tennis",),

     "Я слушаю тебя": ("I listen to you",),
     "Ты слушаешь музыку?": ("Do you listen to music?",),
     "Он не слушает рок": ("He doesn't listen to rock", "He does not listen to rock"),
     "Мы слушали их": ("We listened to them",),
     "Они послушают нас": ("They will listen to us",),
     "Ты не слушал меня": ("You didn't listen to me", "You did not listen to me"),
     "Мы не будем слушать это": ("We will not listen to it", "We won't listen to it"),
     "Она слушала всех": ("She listened to everybody", "She listened to everyone"),
     "Ты слушал наши песни?": ("Did you listen to our songs?",),

     "Ты меня слышишь?": ("Do you hear me?",),
     "Они не услышат нас": ("They won't hear us", "They will not hear us"),
     "Я не слышу тебя": ("I don't hear you", "I do not hear you"),
     "Он не слышал твоих друзей": ("He didn't hear your friends", "He did not hear your friends"),
     "Мы услышим концерт?": ("Will we hear the concert?",),
     "Она услышала их?": ("Did she hear them?",),
     "Я слышал это": ("I heard it",),
     "Ты услышишь сигнал": ("You will hear a signal", "You'll hear a signal"),
     "Она слышит тебя": ("She hears you",),

     "Мы писали письмо": ("We wrote a letter",),
     "Они не напишут нам": ("They will not write us", "They won't write us"),
     "Я пишу музыку": ("I write music",),
     "Он пишет об этом": ("He writes about it",),
     "Она написала рассказ": ("She wrote a story",),
     "Мы не писали в тетради": ("We didn't write in a notebook", "We did not write in a notebook"),
     "Ты будешь писать с нами?": ("Will you write with us?",),
     "Ты пишешь это?": ("Do you write it?",),
     "Он написал книгу?": ("Did he write a book?",),

     "Она написала мне сообщение": ("She texted me a message",),
     "Ты пишешь ей?": ("Do you text her?",),
     "Я напишу им": ("I will text them", "I'll text them"),
     "Не пиши мне": ("Don't text me", "Do not text me"),
     "Она пишет тебе": ("She texts you",),
     "Вы ему написали?": ("Did you text him?",),
     "Я не буду писать это": ("I won't text it", "I will not text it"),
     "Они не писали нам": ("They didn't text us", "They did not text us"),
     "Ты напишешь ей?": ("Will you text her?",),

     "Ты будешь читать?": ("Will you read?",),
     "Мы не будем читать книги": ("We won't read books", "We will not read books"),
     "Я прочитал твоё сообщение": ("I read your message",),
     "Он прочтёт это": ("He will read it",),
     "Вы это читали?": ("Did you read it?",),
     "Он читает об этом?": ("Does he read about it?",),
     "Мы не читали здесь": ("We didn't read here", "We did not read here"),
     "Она читает всё": ("She reads everything",),
     "Я не читаю инструкции": ("I don't read manuals", "I do not read manuals"),
     }
