d = {
     "Что у тебя есть?": ("What do you have?",),
     "Он сказал это вчера": ("He said it yesterday",),
     "Ты идёшь к нам?": ("Do you go to us?",),
     "Мои друзья получили подарки": ("My friends got gifts", "My friends got presents"),
     "Кто сделал суп?": ("Who made the soup?", "Who cooked the soup?"),
     "Мы не знали его": ("We did not know him", "We didn't know him"),
     "Зачем ты думаешь о них?": ("Why do you think about them?",),
     "Кто взял ключи?": ("Who took the keys?",),
     "Я взял их на столе": ("I took them on the table",),
     "Мы видели его с ней": ("We saw him with her",),

     "Ты видел своих родителей?": ("Did you see your parents?",),
     "Они пришли поздно": ("They came late",),
     "Что ты хочешь от меня?": ("What do you want from me?",),
     "Я использовал свой билет": ("I used my ticket",),
     "Я дам тебе немного денег": ("I will give you some money", "I'll give you some money"),
     "Зачем ты ей рассказал эту историю?": ("Why did you tell her this story?",),
     "Мы работали на стройке": ("We worked in construction",),
     "Когда ты ему позвонишь?": ("When will you call him?",),
     "Я попытаюсь ещё раз": ("I will try again", "I'll try again"),
     "Где ты нашёл работу?": ("Where did you find the job?",),

     "Ты подготовился к уроку?": ("Did you prepare for the lesson?",),
     "Я спрошу их": ("I will ask them", "I'll ask them"),
     "Что ты чувствовал тогда?": ("What did you feel then?",),
     "Я стану самым лучшим": ("I will become the best", "I'll become the best"),
     "Когда ты уехал?": ("When did you leave?",),
     "Он положил телефон на стол": ("He put the phone on the table",),
     "Что это значит?": ("What does it mean?",),
     "Я хранил молоко 10 дней": ("I kept milk for 10 days",),
     "Мы начнём завтра": ("We will start tomorrow", "We'll start tomorrow"),
     "Кто им помог?": ("Who helped them?",),

     "Мы показали им картину": ("We showed them the picture?", "We showed them the painting"),
     "Ты меня не слушаешь?": ("Don't you listen to me",),
     "Сколько ты ещё будешь играть в эту игру?": ("How long will you play this game?",),
     "Чемпионы бегают каждый день": ("Champions run every day",),
     "Где она живёт?": ("Where does she live?",),
     "Он верит тебе": ("He trusts you", "He believes you"),
     "Когда ты принесёшь нам еду?": ("When will you bring us food?",),
     "Это произошло вчера": ("What happened yesterday?",),
     "Почему ты не написал ей?": ("Why didn't you text her?",),
     "Где вы сидите?": ("Where do you sit?",),
     }

d_2 = {
     "Почему ты стоишь?": ("Why do you stand?",),
     "Он проиграл не эту игру": ("He did not lose this game", "He didn't lose this game"),
     "Мы встретились в Лондоне": ("We met in London",),
     "Где ты установил эту программу?": ("Where did you set this program?",),
     "Я учил Испанский в детстве": ("I learnt Spanish in childhood", "I learned Spanish in childhood"),
     "Почему она нас не понимает?": ("Why doesn't she understand us?",),
     "Мы не посмотрим этот фильм": ("We will not watch this film", "We won't watch this film"),
     "Когда ты прекратишь?": ("When will you stop?",),
     "Кто оплатит счёт?": ("Who will pay the bill?",),
     "Что ты изменил в своей жизни?": ("What did you change in your life?",),

     "Я создал новую игру": ("I created a new game?",),
     "Кто с тобой разговаривал?": ("Who spoke with you?",),
     "Мой отец читал много книг": ("My father read many books",),
     "Сколько ты потратил на свою машину?": ("How much did you spend on your car?",),
     "Цветы растут на земле": ("Flowers grow on ground",),
     "Когда ты открыл сок?": ("When did you open the juice?",),
     "Кто с ними гулял тогда?": ("Who walked with them then?",),
     "Кто тебя этому научил?": ("Who taught you that?",),
     "Мы выиграли эту игру": ("We won this game",),
     "Ты (разве) не помнишь своего брата?": ("Don't you remember your brother?",),

     "Когда ты купишь новую квартиру?": ("When will you buy a new flat?",),
     "Она мне прислала длинное сообщение": ("She sent me a long message",),
     "Кто построил это здание?": ("Who built this building?",),
     "Они останутся с нами": ("They will stay with us",),
     "Он отрезал торт": ("He cut the cake",),
     "Где он упал?": ("Where did he fall?",),
     "Я убил паука на кухне": ("I killed a spider in the kitchen",),
     "Почему ты продал свою машину?": ("Why did you sell your car?",),
     "Я даже не надеялся": ("I did not even hope", "I didn't even hope"),
     "Твой брат сломал мою машину?": ("Did your brother break my car?",),

     "Я не согласен с тобой": ("I do not agree with you", "I don't agree with you"),
     "Что она делает там?": ("What does she do there?",),
     "Когда ты ел в последний раз?": ("When did you eat last time?",),
     "Ты плавал в детстве?": ("Did you swim in childhood?",),
     "Я не выбирал это": ("I didn't choose it", "I did not choose it"),
     "Кто тебя встретил?": ("Who met you?",),
     "Сколько ты потратил вчера?": ("How much did you spend yesterday?",),
     "Твой друг чувствует это?": ("Does your friend feel it?",),
     "Мы не проиграем": ("We will not lose", "We won't lose"),
     "Ты не пробовал? ": ("Didn't you try?",),
}