d = {"Я выпил": ("I drank",),
     "Они не выпили": ("They didn't drink", "They did not drink"),
     "Ты будешь пить?": ("Will you drink?",),
     "Я не буду пить": ("I will not drink", "I won't drink"),
     "Он не пьёт": ("He doesn't drink", "He does not drink"),
     "Ты пьешь?": ("Do you drink?",),
     "Мы выпьем": ("We will drink",),
     "Вы пили?": ("Did you drink?",),
     "Они не пьют": ("They don't drink", "They do not drink"),

     "Я заплачу": ("I will pay", "I'll pay"),
     "Она не платила": ("She didn't pay", "She did not pay"),
     "Ты не заплатишь": ("You won't pay", "You will not pay"),
     "Мы платим": ("We pay",),
     "Он платит?": ("Does he pay?",),
     "Ты заплатил?": ("Did you pay?",),
     "Они не будут платить": ("They won't pay", "They will not pay"),
     "Мы заплатим?": ("Will we pay?",),
     "Они заплатили": ("They paid",),

     "Они показали": ("They showed",),
     "Мы не покажем": ("We won't show", "We will not show"),
     "Ты показал?": ("Did you show?",),
     "Я покажу": ("I will show", "I'll show"),
     "Они показывают": ("They show",),
     "Мы не показываем": ("We don't show", "We do not show"),
     "Она показывает?": ("Does she show?",),
     "Они не показывают": ("They don't show", "They do not show"),
     "Я не показал": ("I didn't show", "I did not show"),

     "Он купил": ("He bought",),
     "Ты не купил": ("You didn't buy", "You did not buy"),
     "Мы купим": ("We will buy",),
     "Вы покупаете": ("You buy",),
     "Они не будут покупать": ("They will not buy",),
     "Ты купишь?": ("Will you buy?",),
     "Я купил?": ("Did I buy?",),
     "Мы не покупаем": ("We don't buy", "We do not buy"),
     "Он покупает?": ("Does he buy?",),

     "Она получает": ("She gets",),
     "Мы не получим": ("We will not get", "We won't get"),
     "Ты получил?": ("Did you get?",),
     "Я не получаю": ("I don't get", "I do not get"),
     "Мы получили": ("We got",),
     "Они не получили": ("They didn't get", "They did not get"),
     "Ты получишь?": ("Will you get?",),
     "Он получает?": ("Does he get?",),
     "Мы получим": ("We will get", "We'll get"),

     "Вы поняли?": ("Did you understand?",),
     "Мы понимаем": ("We understand",),
     "Я не понимаю": ("I don't understand", "I do not understand"),
     "Мы не поймём": ("We will not understand", "We won't understand"),
     "Ты понял": ("You understood",),
     "Я пойму?": ("Will I understand?",),
     "Вы не поняли": ("You did not understand", "You didn't understand"),
     "Они поймут": ("They will understand",),
     "Они понимают?": ("Do they understand?",),

     "Я отправлю": ("I will send", "I'll send"),
     "Ты не отправляешь": ("You don't send", "You do not send"),
     "Она отправила": ("She sent", ),
     "Он отправит?": ("Will he send?",),
     "Я отправляю": ("I send",),
     "Мы не отправим": ("We won't send", "We will not send"),
     "Ты отправил?": ("Did you send?",),
     "Она отправит?": ("Will she send?",),
     "Они не отправили": ("They didn't send", "They did not send"),

     "Он принесёт": ("He will bring",),
     "Мы не принесли": ("We didn't bring", "We did not bring"),
     "Я приношу": ("I bring",),
     "Ты принесёшь?": ("Will you bring?",),
     "Она не приносит": ("She doesn't bring", "She does not bring"),
     "Ты принёс": ("You brought",),
     "Она приносит?": ("Does she bring?",),
     "Ты принесла?": ("Did you bring?",),
     "Мы не принесём": ("We won't bring", "We will not bring"),

     "Мы пришли": ("We came",),
     "Она приедет": ("She will come",),
     "Он не приходит": ("He doesn't come", "He does not come"),
     "Ты приедешь?": ("Will you come?",),
     "Они не приехали": ("They didn't come", "They did not come"),
     "Мы не приедем": ("We won't come", "We will not come"),
     "Я прихожу": ("I come",),
     "Он пришёл?": ("Did he come?",),
     "Ты приходишь?": ("Do you come?",)
     }